# Generated by Django 5.2.6 on 2025-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_trainingsession_dataset_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='loss',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='data_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='images_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='model_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการ train'), ('processing', 'กำลังสกัดฟีเจอร์'), ('completed', 'เสร็จแล้ว'), ('failed', 'ล้มเหลว')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_name',
            field=models.CharField(max_length=255),
        ),
    ]
