# Generated by Django 5.2.6 on 2025-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_trainingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={},
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='images_used',
            new_name='img_files',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='model_path',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='training_type',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการ train'), ('training', 'กำลัง train'), ('completed', 'train เสร็จแล้ว'), ('failed', 'train ล้มเหลว')], default='pending', max_length=20),
        ),
    ]
