# Generated by Django 5.2.6 on 2025-12-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_trainingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogimage',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='myapp.trainingsession'),
        ),
    ]
