# Generated by Django 5.2.6 on 2025-12-14 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dogimage_training_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='evaluation_plots/')),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='myapp.trainingsession')),
            ],
        ),
    ]
